### ISSUE TITLE
How we can use this in Xamarin

### ISSUE THREAD

**Issue by CDrosos** [4TwentySolutions/FourTwenty.Xamarin.ColorPickerView#1]
Hello,
your nuget package looks very simple and sweet, its what i want
However i can't understand how i can show a colorpicker dialog in xamarin and get the selected string value, can you write a very simple and quick tutorial? with the showDialog code?

**Comment by stepkillah** [comment]
yeah, of course, will extend sample

**Comment by CDrosos** [comment]
you rock and you are fast, 1000 times thank you.
Can this used to only select a color without using an image? i just want to select a color but not from an image (the ColorPickerDialog is what i want from the java example)

**Comment by stepkillah** [comment]
@CDrosos you can check for example in ([root repo](https://github.com/skydoves/ColorPickerView)), it's almost the same in Xamarin.

I also added a bit extended example in this repo, you can check `FourTwenty.Xamarin.ColorPickerView.Sample` project.

you can use picker without any images, just use `palette` and `wheel` drawable (see in the example)
