### ISSUE TITLE
Moving the pointer of the color picker at the end of the left or right does not appear correctly

### ISSUE THREAD

**Issue by CDrosos** [4TwentySolutions/FourTwenty.Xamarin.ColorPickerView#2]
I'm using this code:

        ```
private void ShowDialogBtnOnClick(object sender, EventArgs e)
        {

            var builder = new ColorPickerDialog.Builder(this);
            builder.SetTitle(GetString(Resource.String.Options_ColorText));
            builder.SetPreferenceName("TextColorPicker");
            builder.SetPositiveButton(GetString(Resource.String.All_SaveButton), this);
            builder.SetNegativeButton(GetString(Resource.String.All_CancelButton), this);
            builder.AttachBrightnessSlideBar(true);
            builder.AttachAlphaSlideBar(true)
            .Show();
        }
```

And i have this result,
https://drive.google.com/file/d/1Yf6cLZzDrQTJztcsj9FLbzzOuaqGQE4B/view?usp=sharing
 the color picker in the end appears half cicle, am i doing something wrong?

**Comment by stepkillah** [comment]
@CDrosos when you try to run the sample from this repo - it behaves the same? this is just a binding for colorpicker lib, the sample displays correctly on my device and simulators, also we use it in several apps - works well.
Also, be aware of using `builder.SetPreferenceName("TextColorPicker");` as it will set previously settled value.
